name: Build Gem80

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - keyboards/nuphy/gem80/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Firmware
        uses: justgook/qmk-build@v1
        with:
          keymap-path: "keyboards/nuphy/gem80/ansi/keymaps/via"
          keyboard: "nuphy/gem80/ansi"
          keymap: "via"

      - name: Upload a Firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware
          path: build
